version: '2'
services:
 omsa:
    container_name: omsa
    build: ./build/.
    image: dilanodroog/omsa
    network_mode: "host"
    restart: unless-stopped
    cap_add:
     - ALL
    privileged: true
    volumes:
      - "/lib/modules:/lib/modules:ro"
